### ISSUE TITLE
Can't build Qt version

### ISSUE THREAD

**Issue by tuaris** [ppcoin/ppcoin#89]
The daemon version build fine.
When I try to build the Qt wallet I am getting:

```
src/qt/transactiondesc.cpp:247:19: error: variable has incomplete type 'CTxDB'
            CTxDB txdb("r"); // To fetch source txouts
                  ^
src/main.h:98:7: note: forward declaration of 'CTxDB'
class CTxDB;
      ^
````

**Comment by FuzzyBearBTC** [comment]
@tuaris  can you build the daemon with no errors? Its good to check you have the general dependencies working fine with the daemon build first, then try the Qt, will give us some better insight into what is going on as I have not seen this error before

**Comment by tuaris** [comment]
The non Qt daemon builds and works fine.  FYI, this is FreeBSD 9.3 and 10.x.

**Comment by tuaris** [comment]
This is the build log for the daemon
http://pkg.morante.net/poudriere/data/93amd64-default-wallets/latest-per-pkg/ppcoin-0.4.0.0_1.log

**Comment by FuzzyBearBTC** [comment]
@tuaris Ah I have not tried to build on FreeBSD.

If your daemon working then that is good, not an issue with core dependencies.  

Now check your Qt deps... what versions are you running I know there are some issues from certain QT-creator versions etc

I have found this https://www.peercointalk.org/index.php?topic=1917.5 where user d5000 reported same error as you but on Linux system.
Solution was https://www.peercointalk.org/index.php?topic=1917.msg15555#msg15555

**Comment by tuaris** [comment]
I couldn't find what the solution was on the link you provided.  Looks like it was not solved at the end.  I was able to find an old Bitcoin discussion regarding the same error: http://bitcoinstats.com/irc/bitcoin-dev/logs/2012/05/28#l1338241436.0 It seems to mention that an #include is needed somewhere but they also don't offer a solution.

This is strange, I am able to build lots of other Qt wallets just fine.

**Comment by tuaris** [comment]
I got it.  Found an old patch for Bitcoin 0.6.3 at https://svnweb.freebsd.org/ports/head/net-p2p/bitcoin/files/patch-transactiondesc.cpp?view=markup&pathrev=303526.  

Need to add to 'transactiondesc.cpp':

```
#include "walletdb.h"
```

Now on to the next issue

```
collect2: error: ld returned 1 exit status
```
