### ISSUE TITLE
Current master sends change to the input address with avatar mode disabled

### ISSUE THREAD

**Issue by sigmike** [ppcoin/ppcoin#96]
An exchange reported that change is (maybe only sometimes) sent to the input address while avatar mode is not enabled. The problem would be present in commit 650ea5f, but not in 6219e88. I can't verify that right now.

**Comment by Mullick** [comment]
I can verify this issue. Coming from our wallet with no avatar mode set in the config file
31968e024cc4a29a3890a2832e4c04fe5f0096c69a630398869d004b68a4fc65
Sent its change back to the input address.

**Comment by glv2** [comment]
I made PR #97 which seems to fix the issue.
Can someone else try and confirm?

**Comment by mably** [comment]
Looks like it's coming from here ;)

https://github.com/glv2/peerunity/commit/364fa630

**Comment by sunnyking** [comment]
Fixed in #97 by glv2.
